import { DefineFunction, Schema } from "deno-slack-sdk/mod.ts";

/**
 * Custom function that saves a new member's masterdata and bank details,
 * posts a vCard contact card to the admin channel, and returns the SEPA
 * mandate details generated by the masterdata backend.
 */
export const SaveNewMemberFunction = DefineFunction({
  callback_id: "masterdata_save_new_member",
  title: "Neues Mitglied speichern",
  description:
    "Speichert ein neues Mitglied in den Stammdaten und der SEPA-Datei",
  source_file: "src/masterdata/functions/save_new_member/mod.ts",
  input_parameters: {
    properties: {
      joinedDate: {
        type: Schema.slack.types.date,
        description: "Eintrittsdatum",
      },
      firstname: { type: Schema.types.string, description: "Vorname" },
      lastname: { type: Schema.types.string, description: "Nachname" },
      email: { type: Schema.types.string, description: "E-Mail-Adresse" },
      phone: { type: Schema.types.string, description: "Telefonnummer" },
      birthday: {
        type: Schema.slack.types.date,
        description: "Geburtsdatum",
      },
      street: { type: Schema.types.string, description: "Straße" },
      houseNumber: { type: Schema.types.string, description: "Hausnummer" },
      zip: { type: Schema.types.string, description: "Postleitzahl" },
      city: { type: Schema.types.string, description: "Stadt" },
      sex: { type: Schema.types.string, description: "Geschlecht (m oder w)" },
      membershipType: {
        type: Schema.types.string,
        description: "Mitgliedschaftsart (aktiv, ermäßigt oder passiv)",
      },
      IBAN: { type: Schema.types.string, description: "IBAN" },
      BIC: { type: Schema.types.string, description: "BIC" },
      accountOwner: {
        type: Schema.types.string,
        description:
          "Kontoinhaber, falls abweichend vom Mitglied (sonst leer lassen)",
      },
      signingDate: {
        type: Schema.slack.types.date,
        description: "Datum der SEPA-Mandat-Unterschrift",
      },
      adminChannel: {
        type: Schema.slack.types.channel_id,
        description: "Channel, in dem die Kontaktkarte gepostet wird",
      },
    },
    required: [
      "joinedDate",
      "firstname",
      "lastname",
      "email",
      "phone",
      "birthday",
      "street",
      "houseNumber",
      "zip",
      "city",
      "sex",
      "membershipType",
      "IBAN",
      "BIC",
      "signingDate",
      "adminChannel",
    ],
  },
  output_parameters: {
    properties: {
      mandateReference: {
        type: Schema.types.string,
        description: "SEPA-Mandatsreferenz",
      },
      initialAmount: {
        type: Schema.types.string,
        description: "Erstbetrag",
      },
      recurringAmount: {
        type: Schema.types.string,
        description: "Wiederkehrender Betrag",
      },
      contactCardMessageLink: {
        type: Schema.types.string,
        description: "Link zur geposteten Kontaktkarte",
      },
    },
    required: [
      "mandateReference",
      "initialAmount",
      "recurringAmount",
      "contactCardMessageLink",
    ],
  },
});
